spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_service?serverTimezone=Europe/Bucharest
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
