server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: car-rental-service
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_service?serverTimezone=Europe/Bucharest
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
