server:
  port: ${PORT:8071}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
  name: swift-wheels-hub
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/swift-wheels-hub
          jwk-set-uri: http://localhost:8080/realms/swift-wheels-hub/protocol/openid-connect/certs
        client:
          provider:
            keycloak:
              issuer-uri: http://localhost:8080/realms/swift-wheels-hub
              user-name-attribute: preferred_username
          registration:
            keycloak:
              client-id: swift-wheels-hub
              authorization-grant-type: authorization_code
              provider: keycloak
              scope: openid,profile,email,offline_access
  datasource:
    url: jdbc:mysql://localhost:3306/swift_wheels_hub?serverTimezone=Europe/Bucharest
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          csrf:
            CsrfFilter: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

keycloak:
  serverUrl: http://localhost:8080
  realm: ${KEYCLOAK_REALM}
  clientId: ${KEYCLOAK_CLIENT_ID}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET}
