server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false

spring:
  application: car-rental-service
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental_service?serverTimezone=Europe/Bucharest
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
